# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-01-24 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=15)),
                ('Class_date', models.DateTimeField()),
            ],
        ),
    ]
