# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-01-24 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellingportal', '0002_myclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_drgee', models.IntegerField(default=15)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellingportal.Student')),
            ],
        ),
        migrations.DeleteModel(
            name='MyClass',
        ),
    ]
